debug run token

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -29,7 +29,12 @@ jobs:
         run: echo "short_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
       - env:
           GH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
-        run: envsubst '${GH_TOKEN}' < .github/ci/settings.xml.template > abc_data.xml
+        run: |
+          envsubst '${GH_TOKEN}' < .github/ci/settings.xml.template > abc_data.xml
+          if grep -q '\${GH_TOKEN}' abc_data.xml; then
+            echo "ERROR: GH_TOKEN was not substituted!"
+            exit 1
+          fi
       - uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
